#!/bin/bash

# load all the env vars for this display
source "$MONITOR_BASE_FOLDER""/config.xinitrc"

# set the appropriate dpi
xrandr --dpi 96x96

# set the background colour to the one in the global config
xsetroot -solid "$BG_COLOUR" &

# start the window manager
mywindowmanager
